version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t anuragnandan/dolores:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push anuragnandan/dolores:$TAG
